Refactor
KoTuK2306/Testing pull request #13
Opened 2022-03-21 07:24 UTC by KoTuK2306

2022-03-21 08:10 UTC, pavelsokolov21 requested changes

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/App.js
> +import { useState, useEffect } from "react";
сначала либы, потом компоненты

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/ConfirmationWindow/ConfirmationWindow.jsx
> +        <button onClick={() => setDisplay("none")} className={classes.falseButton + " " + classes.trueButton}>
шаблонная строка

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/ConfirmationWindow/ConfirmationWindow.jsx
> +    <div className={classes.window} style={{ display: display }}>
inline styles выглядит некруто. Лучше используй модификаторы из методологии BEM. Тем более, я так понимаю, что `display` принимает только 2 значения. Тем самым, ты можешь сделать класс `window_open`, который не будет зависить от дисплея

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/ConfirmationWindow/ConfirmationWindow.jsx
> +          className={classes.trueButton}
`buttonSuccess`

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/ConfirmationWindow/ConfirmationWindow.jsx
> +export const ConfirmationWindow = ({ display, setDisplay, deleteUser }) => {
это `ConfirmationWindow`

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/ConfirmationWindow/ConfirmationWindow.jsx
> +            setDisplay("none");
мне не нравится, что `setDisplay` прилетает сюда как проп. Мы управляем модалкой извне с помощью `useState`, что не круто. Если тебе нужно открывать это извне, посмотри в сторону `react context API`. Так ты не будешь втупую прокидывать пропы

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/Pagination/Pagination.jsx
> +          className={currentPage === number ? classes.pageLink + " " + classes.active : classes.pageLink}
шаблонная строка

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/Pagination/Pagination.jsx
> +export const Pagination = ({ usersPerPage, totalUsers, paginate, currentPage }) => {
в теории, пагинация могла бы использоваться не только для юзеров, поэтому подвязывать такой компонент под них не совсем правильно. В данном случае лучше использовать более абстрактные названия

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/SearchBlock/ClearFilter/ClearFilter.jsx
> +      <p onClick={() => clearFiltering()}>Очистить фильтр</p>
достаточно 
```jsx
<p onClick={clearFiltering}>Очистить фильтр</p>
```

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/ConfirmationWindow/ConfirmationWindow.module.css
> +  background-color: #e0e0e0;
я видел, что ты использовать переменные, но здесь все равно в хексе. Как так?

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/SearchBlock/Search/Search.jsx
> +import React from "react";
тут импорт реакта не нужен

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/SearchBlock/Search/Search.jsx
> +      onChange={(text) => inputedText(text)}
event

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/SearchBlock/Search/Search.jsx
> +  const inputedText = (text) => {
event

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/SearchBlock/SearchBlock.jsx
> +import { useState } from "react";
сначала либы

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/SearchBlock/Search/Search.jsx
> +      placeholder="Поиск по имени или e-mail"
я бы `placeholder` сделал как проп тоже

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/UsersBlock/UsersBlock.jsx
> +import { useState } from "react";
сначала либы

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/UsersBlock/UsersBlock.jsx
> +  const [i, setI] = useState(0);
выглядит очень страшно. Переделай на `ASC/DESC`

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/UsersBlock/UsersBlock.jsx
> +  const [currentButton, setCurrentButton] = useState("");
что такое `currentButton`? Нужно более четкое название

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/UsersBlock/UsersList/User/User.jsx
> +var _ = require("lodash");
тебе въебать? Какой вар через рекваер? Сделай нормальный импорт, плз)

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/UsersBlock/UsersList/User/User.jsx
> +import { useState } from "react";
сначала либы

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/UsersBlock/UsersList/User/User.jsx
> +    if (userIndex > -1) setUsers(_.difference(users, filteredUsers.splice(userIndex, 1)));
лучше юзать скобки для `if`. Так будет более читабельно

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/UsersBlock/UsersList/UsersList.jsx
> +import React, { useState } from "react";
сначала либы

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/UsersBlock/UsersList/UsersList.jsx
> +  const [usersPerPage] = useState(5);
смысл состояния, если его не менять? Пусть будет константа (вне компонента)

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/Pagination/Pagination.jsx
> +import classes from "./Pagination.module.css";
нет индекс файла для этого компонента

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/SearchBlock/ClearFilter/ClearFilter.jsx
> +      <img src={clearIcon} alt="Clear Icon"></img>
на самом деле, ты можешь запихнуть картинки в `public`. Тем самым, тебе не надо будет импортировать сюда картинку. Например, в `public` будет `images/clearIcon.png`. Тогда 
```jsx
<img src="/images/clearIcon.png" alt="Clear Icon" />
```

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/App.js
> +  const [filtering, setFiltering] = useState("");
попробуй сделать это же логику, но через `React Context API`. Тем самым будет выглядить это чудо приличнее

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/SearchBlock/Search/Search.module.css
> +  background-image: url("../../../images/searchIcon.png");
посмотри коммент про папку `public`

2022-03-21 08:10 UTC, pavelsokolov21 commented on src/components/UsersBlock/UsersList/User/User.module.css
> +  font-weight: 700 !important;
осуждаю. Думай, как сделать без этого

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/SearchBlock/Search/Search.jsx
> +  const contextValues = useContext(FilteringContext);
```suggestion
  const { setFiltering }= useContext(FilteringContext);

```

2022-03-23 14:47 UTC, KoTuK2306 commented on src/App.js
> +  const [filtering, setFiltering] = useState("");
это же `search`

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/SearchBlock/Search/Search.jsx
> +    setText(event.target.value);
оно нахуй тут не нужно

2022-03-23 14:47 UTC, KoTuK2306 commented on src/App.js
> +export const FilteringContext = React.createContext({});
вынести контекст в папку

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/ConfirmationModal/ConfirmationModal.jsx
> +  console.log(contextValues);
удалить

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/User/User.jsx
> +export const isOpenContext = React.createContext({});
Это `ModalContext`. Вынести в отдельную папку

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/User/User.jsx
> +  const [openWindow, setOpenWindow] = useState(false);
```suggestion
  const [isOpened, setIsOpened] = useState(false);

```

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/User/User.jsx
> +              console.log(openWindow);
удалить

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/User/User.jsx
> +            onClick={() => {
вынеси эту функцию в контекст модалки

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/User/User.jsx
> +            src={process.env.PUBLIC_URL + "/images/delete.png"}
я бы создал util-function, которая будет добавлять этот энв к картинкам

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/User/User.module.css
> +  width: calc((925px - 18px) / 4);
что за 18px?

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/UsersList.module.css
> +  color: #acacac;
переменные

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.jsx
> +        <p onClick={() => sortByDate("byRegistrationDate")} className={setClass("byRegistrationDate")}>
нужно вынести эти кнопки в компоненты, чтобы было адекватное состояние `asc/desc`

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.jsx
> +  const sortByDate = (option) => {
вынеси в отдельную функцию общую логику и пусть она принимает функцию, которая будет сортировать

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/UsersList.jsx
> +  const filteredUsersBeforePagination = users.filter((user) => {
```suggestion
  const filteredUsersBeforePagination = users.filter(({ username, email }) => {

```

2022-03-23 14:47 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/UsersList.jsx
> +  const contextValues = useContext(FilteringContext);
```suggestion
  const { filtering }= useContext(FilteringContext);

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/ConfirmationModal/ConfirmationModal.jsx
> +    <div className={`${useModal().isOpened ? classes.window_open : classes.window_closed} ${classes.window}`}>
используй хук выше

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/ConfirmationModal/ConfirmationModal.jsx
> +      <div className={classes.ConfirmationModal}>
```suggestion
      <div className={classes.confirmationModal}>

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/ConfirmationModal/ConfirmationModal.jsx
> +export const ConfirmationModal = ({ deleteUser }) => {
Либо измени название, чтобы указать, что это модалка удаления, либо сделай модалку более общей

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/ConfirmationModal/ConfirmationModal.module.css
> +  background-color: #fff;
бери цвета из темы

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/ConfirmationModal/ConfirmationModal.module.css
> +  color: #000;
бери цвета из темы

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/ConfirmationModal/ConfirmationModal.module.css
> +  background-color: var(--succesButtonColor);
`successButtonColor`

2022-03-25 10:14 UTC, KoTuK2306 commented on src/colors.css
> +  --falseButtonColor: #0cb4f1;
придумай более общие названия цветов

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/ConfirmationModal/ConfirmationModal.module.css
> +.window_open {
```suggestion
.modal_open {

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/ConfirmationModal/ConfirmationModal.module.css
> +.window_closed {
```suggestion
.modal_closed {

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/Pagination/Pagination.jsx
> +  let pageNumbers = [];
```suggestion
  const pageNumbers = [];

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/Pagination/Pagination.module.css
> +  background-color: #f7f7f7;
цвета из темы

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/SearchBlock/ClearFilter/ClearFilter.module.css
> +  color: #4f4f4f;
цвета из темы

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/SearchBlock/Search/Search.jsx
> +  const inputedText = (event) => setSearch(event.target.value);
```suggestion
  const onChange = (event) => setSearch(event.target.value);

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/SearchBlock/Search/Search.jsx
> +      className={classes.Search}
```suggestion
      className={classes.search}

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/SearchBlock/Search/Search.module.css
> +  background: #eceff0;
цвета из темы

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/SearchBlock/SearchBlock.module.css
> +.SearchBlock {
```suggestion
.searchBlock {

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/SearchBlock/SearchBlock.module.css
> +  background: #ffffff;
цвета из темы

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/Title/Title.module.css
> +  color: #333333;
цвета из темы

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/SortButton/SortButton.jsx
> +    <button className={className} onClick={() => onClick()}>
```suggestion
    <button className={className} onClick={onClick)}>

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.jsx
> +        <SortButton onClick={() => sort("byRegistrationDate", sortByDate)} className={setClass("byRegistrationDate")}>
```suggestion
        <SortButton onClick={() => sort("byRegistrationDate", sortByDate)} className={`classes.sorting ${currentSort === 'byRegistrationDate' ? classes.sorting_active : ''}`}>

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.jsx
> +  const setClass = (currentSorting) => {
эта функция выглядит бесплезной. Смотри пример выше

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.jsx
> +  const sort = (option, howSort) => {
`howSort` плохое название, тк не подразумевает функцию

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.jsx
> +  const [sortMethod, setSortMethod] = useState(DESC);
```suggestion
  const [order, setOrder] = useState(DESC);

```

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.module.css
> +  border-bottom: 1px dashed #333333;
цвет из темы

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.jsx
> +        <SortButton onClick={() => sort("byRate", sortByRating)} className={setClass("byRate")}>
аналогично про сортировку

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/User/User.module.css
> +  border-bottom: 1px solid #f7f7f7;
цвет из темы

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/User/User.module.css
> +  width: calc((925px - var(--userRightMargin)) / 4);
почему 4? используй переменную

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/UsersList.jsx
> +import { Pagination } from "../../Pagination/Pagination";
у тебя же есть в этой папке `index.js`

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/UsersList.module.css
> +  background: #ffffff;
цвет из темы

2022-03-25 10:14 UTC, KoTuK2306 commented on src/components/ConfirmationModal/ConfirmationModal.module.css
> +.ConfirmationModal {
```suggestion
.confirmationModal {

```

2022-03-26 12:32 UTC, KoTuK2306 commented on src/components/DeleteUserConfirmationModal/DeleteUserConfirmationModal.module.css
> +  color: #828282;
цвет из темы

2022-03-26 12:32 UTC, KoTuK2306 commented on src/components/DeleteUserConfirmationModal/DeleteUserConfirmationModal.module.css
> +  color: #fff;
цвет из темы

2022-03-26 12:32 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.jsx
> +    } else {
используй `return`

2022-03-26 12:32 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.jsx
> +    } else {
пустой `return`

2022-03-26 12:32 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersBlock.jsx
> +          onClick={() => sort("byRegistrationDate", sortByDate)}
вынеси в константы `byRegistrationDate` и `byRate`

2022-03-26 12:32 UTC, KoTuK2306 commented on src/components/UsersBlock/UsersList/UsersList.module.css
> +  width: calc((925px - 18px) / 4);
4 - магическое число

2022-03-26 16:51 UTC, closed without merging

2022-03-26 17:01 UTC, pavelsokolov21 approved these changes